name: curso_dart_ed_team
description: A simple command-line application.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  test: 1.17.4
  
dev_dependencies:
  random_string: ^2.1.0

scripts:
  saludo:
    - echo "Hola mundo"
  importar:
    - pub get
    - pub upgrade
    - echo "Las dependencias estan actualizadas"