name: curso_dart_ed_team
description: A simple command-line application.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  random_string: ^2.1.0

dev_dependencies:
  pedantic: ^1.9.0
